version: 2.1
 
orbs:
  android: circleci/android@0.2.1
 
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
        environment:
          JVM_OPTS: -Xmx3200m
          JAVA_HOME: /usr/lib/jvm/zulu-17-amd64
    executor: android/android

    steps:
      - checkout
      - run:
          name: Update Java version
          command: |
            sudo update-alternatives --set java /usr/lib/jvm/zulu-17-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/zulu-17-amd64/bin/javac
      - run:
          name: Run Code Coverage
          command: ./gradlew jacocoTestReport
      - run:
          name: Check Code Style
          command: ./gradlew detekt ktlint
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
